name: Update AdGuard Blocklist (dist branch)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "17 3 * * *"  # daily @ 03:17 UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      OUTPUT_FILE: adguard_blocklist.txt
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate blocklist
        env:
          OUTPUT_FILE: adguard_blocklist.txt
          SOURCES_FILE: sources.txt
          ALLOWLIST_FILE: allowlist.txt
          EXTRAS_BLOCK_FILE: extras_block.txt
          ENABLE_SUBSUMPTION: "1"
        run: |
          python convert_hosts.py
          ls -lh adguard_blocklist.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: adguard-blocklist
          path: adguard_blocklist.txt
          if-no-files-found: error
          retention-days: 1

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (for dist branch ops)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: adguard-blocklist
          path: .

      - name: Prepare dist branch
        run: |
          set -e
          git fetch origin +refs/heads/dist:refs/remotes/origin/dist || true
          if git show-ref --verify --quiet refs/remotes/origin/dist; then
            echo "dist branch exists."
            git checkout -B dist origin/dist
          else
            echo "Creating dist branch."
            # create orphan so dist contains only built files
            git checkout --orphan dist
            # remove everything from index
            git rm -rf . || true
          fi

      - name: Place built artifacts in dist root
        run: |
          set -e
          # keep only the final deliverable(s) on dist
          find . -mindepth 1 -maxdepth 1 ! -name 'adguard_blocklist.txt' -exec rm -rf {} +
          git add adguard_blocklist.txt

      - name: Commit if changed (dist)
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git commit -m "dist: update blocklist ($(date -u +'%Y-%m-%dT%H:%M:%SZ'))"
            git push origin dist
          else
            echo "No changes on dist."
          fi
